### ISSUE TITLE
Add setting of keyboard key 

### ISSUE THREAD

**Issue by AlexByte** [YujiSoftware/copy-text-without-selecting-chrome#1]

**Comment by YujiSoftware** [comment]
Currently, "Alt + click" is supported for copying text.
Is your request a different key mapping?

**Comment by AlexByte** [comment]
Yes, it's a request for a different key mapping.

**Comment by YujiSoftware** [comment]
Alright, I will try to be able to choose "Ctrl + Click" or "Shift + Click" as well.

**Comment by AlexByte** [comment]
Maybe also bring back opportunity to copy with context menu.

**Comment by YujiSoftware** [comment]
Please tell me more in detail...
Is it better to be able to copy on the context menu because it is more convenient for one hand to operate? Or another reason?

**Comment by AlexByte** [comment]
Yes, sometimes it is more convenient

**Comment by YujiSoftware** [comment]
Add setting of modified key!

This feature has already been released.
It will be updated to your Google Chrome soon.

Context menu may be bring back with #2.

**Comment by AlexByte** [comment]
Can be to add support for a click with the right mouse button?
